---
# Source: helm for kubernetes/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pheng-bunath-d3248871                  # Ingress name
  labels:
    app: pheng-bunath-d3248871
spec:
  ingressClassName: nginx   # Optional ingressClass
  rules:
    - host: "pheng-bunath-d3248871.smartops.space"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pheng-bunath-d3248871               # Links to Service name dynamically
                port:
                  number: 3000  # Links to service port dynamically
